---
title: "7. 도서관 대출도서 정보"
output: html_notebook
---


공공도서과 대출 상위 목록은 도서관 정보 나루에서 가져올 수 있다.

http://data4library.kr/

베스트셀로는 교보문고에서 월간 기준으로 가져올 수 있다.


도서관 정보 나루에서 API 인증키를 받아 Data를 받아보기

```{r}
install.packages('httr')

library(httr)

key<-'97c02bfe25c0de474e9dbb83f84b2abcabd0fb8425c74cdac87222093632466e'
url<-paste0("http://data4library.kr/api/loadItemSrch?authKey=", key , "&startDt=2019-12-01&endDt=2019-12-22")

GET(url)

```

아직 승인이되지 않아 사용을 못함. 
Status가 200 이어야 정상상태임.


###########################################
2019년 1월부터 2019년 12월까지 월별로 도서관 정보나루에서 인기대출도서 200위를 받아서 별도 파일에 저장하기
###########################################

```{r}
library(httr)
start_date<-seq(as.Date("2019-01-01"), as.Date("2019-12-01"), by="month")
end_date<-start_date-1
baseURL<-"http://data4library.kr/api/loanItemSrch?authKey=97c02bfe25c0de474e9dbb83f84b2abcabd0fb8425c74cdac87222093632466e&format=json"
#baseURL<-"http://data4library.kr/api/loanItemSrch?authKey=97c02bfe25c0de474e9dbb83f84b2abcabd0fb8425c74cdac87222093632466e"

for(d in 1:11)
{
  r<-GET(baseURL, query=list(startDt=start_date[d], endDt=end_date[d+1]))
  t<-data.frame(ranking=integer(), bookname=character(), authors=character(), count=integer(), isbn=character(), stringsAsFactors = F)
  cnt<-content(r, "parsed")
  for(i in 1:200)
  {
    t[nrow(t)+1,]<-c(cnt$response$docs[[i]]$doc$ranking, cnt$response$docs[[i]]$doc$bookname, cnt$response$docs[[i]]$doc$authors,cnt$response$docs[[i]]$doc$loan_count, cnt$response$docs[[i]]$doc$isbn13)
  }
  fn<-paste("output", start_date[d],sep="/")
  fn<-paste(fn, "csv", sep=".")
  write.table(t, fn, sep="|")
}

```


============================================
교보문고 베스트셀러 가져오기
http://www.kyobobook.co.kr/bestSellerNew/bestseller.laf에 있다고 함


```{r}
library(rvest)


baseURL<-"data/교보문고_종합 베스트_월간_2019년_11월_분야 종합201912242259.xls"


kb<-read_html(baseURL, encoding="cp949")

kb %>% html_table()
t<-html_table(kb)
str(t)

t2<-t[[1]]
str(t2)
t3<-t2[-c(1,2,3)]
t3<-t2
str(t3)
t2[c(2),]
colnames(t3)<-t2[c(2),]
t2[c(2),]
str(t3)
t3<-t3[-c(1,2,3),]
str(t3)

write.csv(t3,"data/bestseller.csv")

```

=========================
도서관 대출인기도서와 교보문고 베스트셀러 상관성 조사
=========================

```{r}
library(rvest)
library(plyr)

loan<-seq(as.Date("2015-03-01"), as.Date("2017-06-01"), by="month")
seller<-seq(as.Date("2014-04-01"), as.Date("2017-06-01"), by="month")

count<-c()
for(i in 1:28)
{
  loan_file<-paste("data/bestseller", loan[i], sep="/")
  loan_file<-paste(loan_file, "csv", sep=".")
  loan_table<-read.csv(loan_file, header=T, sep="|", colClasses=c("isbn"="character"))
  for(j in 0:11)
  {
    seller_file<-paste("data/bestseller/kb", seller[i+j], sep="-")
    seller_file<-paste(seller_file, "xls", sep=".")
    seller_html<-read_html(seller_file, encoding="cp949")
    t<-html_table(seller_html)
    t2<-t[[1]]
    t3<-t2[-c(1,2,3),]
    colnames(t3)<-t2[c(2),]
    if(j==0) {
      seller_table<-t3
      
    }
    else
    {
      seller_table<-rbind(seller_table, t3)
      
    }
  }
  seller_table2<-ddply(seller_table, c("ISBN"), summarize, num=length(ISBN))
  colnames(seller_table2)[1]<-"isbn"
  count<- c(count, nrow(merge(loan_table, seller_table2, by="isbn")))
}

loan_seller<-data.frame(loan, count)

library(ggplot2)
ggplot(loan_seller, aes(loan, count)) + geom_bar(stat="identity")

```


```{r}
head(seller_table2)

```




